/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Obj {
  /**
   * 字典标识
   */
  dictId: number;
  /**
   * 编码
   */
  code: string;
  /**
   * 类型
   */
  type: string;
  /**
   * 有效范围
   */
  text: string;
  /**
   * 名称
   */
  scope: string;
  /**
   * 排号
   */
  rank: number;
  /**
   * 状态
   */
  status: number;
  /**
   * 父亲
   */
  parent: number;
  /**
   * 祖先
   */
  ancestors: string;
  /**
   * 深度
   */
  depth: number;
  /**
   * 叶子
   */
  terminal: number;
  [k: string]: unknown;
}
