/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 字典项目列表
 */
export type DictsDictIditemsGetResponse = {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除？
   */
  deteled?: boolean;
  [k: string]: unknown;
}[];
/**
 * 字典列表
 */
export type DictsGetResponse = {
  /**
   * 标识
   */
  id: number;
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  text: string;
  /**
   * 描述
   */
  description: string;
  /**
   * 状态
   */
  status: number;
  /**
   * 删除？
   */
  deleted: boolean;
  [k: string]: unknown;
}[];
export type DictsDictCodeitemsByCodeGetResponse = {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除
   */
  deleted?: boolean;
  [k: string]: unknown;
}[];

export interface Api {
  EditUserInfoPostParams?: EditUserInfoPostParams;
  EditUserInfoPostResponse?: EditUserInfoPostResponse;
  LoginGetParams?: LoginGetParams;
  LoginGetResponse?: LoginGetResponse;
  DictDictIditemsItemIdGetParams?: DictDictIditemsItemIdGetParams;
  DictDictIditemsItemIdGetResponse?: DictDictIditemsItemIdGetResponse;
  DictsDictIditemsItemIdPutParams?: DictsDictIditemsItemIdPutParams;
  DictsDictIditemsItemIdPutResponse?: DictsDictIditemsItemIdPutResponse;
  DictsDictIditemsItemIdDeleteParams?: DictsDictIditemsItemIdDeleteParams;
  DictsDictIditemsItemIdDeleteResponse?: DictsDictIditemsItemIdDeleteResponse;
  DictsDictIditemsPostParams?: DictsDictIditemsPostParams;
  DictsDictIditemsPostResponse?: DictsDictIditemsPostResponse;
  DictsDictIditemsGetParams?: DictsDictIditemsGetParams;
  DictsDictIditemsGetResponse?: DictsDictIditemsGetResponse;
  DictsPostParams?: DictsPostParams;
  DictsPostResponse?: DictsPostResponse;
  DictsGetParams?: DictsGetParams;
  DictsGetResponse?: DictsGetResponse;
  DictsDictIdDeleteParams?: DictsDictIdDeleteParams;
  DictsDictIdDeleteResponse?: DictsDictIdDeleteResponse;
  DictsDictIdPutParams?: DictsDictIdPutParams;
  DictsDictIdPutResponse?: DictsDictIdPutResponse;
  DictDictIdGetParams?: DictDictIdGetParams;
  DictDictIdGetResponse?: DictDictIdGetResponse;
  DictsDictIditemsAsPageGetParams?: DictsDictIditemsAsPageGetParams;
  DictsDictIditemsAsPageGetResponse?: DictsDictIditemsAsPageGetResponse;
  DictsDictCodeitemsByCodeGetParams?: DictsDictCodeitemsByCodeGetParams;
  DictsDictCodeitemsByCodeGetResponse?: DictsDictCodeitemsByCodeGetResponse;
  DictsAsPageGetParams?: DictsAsPageGetParams;
  DictsAsPageGetResponse?: DictsAsPageGetResponse;
  [k: string]: unknown;
}
export interface EditUserInfoPostParams {
  /**
   * 名字
   */
  userName: string;
  /**
   * 年龄
   */
  age: number;
  /**
   * 地址
   */
  address: string;
  [k: string]: unknown;
}
export interface EditUserInfoPostResponse {
  /**
   * 名字
   */
  userName: string;
  /**
   * 年龄
   */
  age: number;
  /**
   * 地址
   */
  field_12address: string;
  [k: string]: unknown;
}
export interface LoginGetParams {
  username: string;
  password: string;
  [k: string]: unknown;
}
export interface LoginGetResponse {
  username: string;
  password: string;
  age: string;
  [k: string]: unknown;
}
export interface DictDictIditemsItemIdGetParams {
  [k: string]: unknown;
}
export interface DictDictIditemsItemIdGetResponse {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除？
   */
  deleted?: boolean;
  [k: string]: unknown;
}
export interface DictsDictIditemsItemIdPutParams {
  [k: string]: unknown;
}
export interface DictsDictIditemsItemIdPutResponse {
  /**
   * 字典标识
   */
  id?: number;
  /**
   * 字典项目标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除？
   */
  deteled?: boolean;
  [k: string]: unknown;
}
export interface DictsDictIditemsItemIdDeleteParams {
  [k: string]: unknown;
}
export interface DictsDictIditemsItemIdDeleteResponse {
  [k: string]: unknown;
}
export interface DictsDictIditemsPostParams {
  /**
   * 字典标识
   */
  dictId: number;
  /**
   * 编码
   */
  code: string;
  /**
   * 类型
   */
  type: string;
  /**
   * 有效范围
   */
  text: string;
  /**
   * 名称
   */
  scope: string;
  /**
   * 排号
   */
  rank: number;
  /**
   * 状态
   */
  status: number;
  /**
   * 父亲
   */
  parent: number;
  /**
   * 祖先
   */
  ancestors: string;
  /**
   * 深度
   */
  depth: number;
  /**
   * 叶子
   */
  terminal: number;
  [k: string]: unknown;
}
export interface DictsDictIditemsPostResponse {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除？
   */
  deleted?: boolean;
  [k: string]: unknown;
}
export interface DictsDictIditemsGetParams {
  [k: string]: unknown;
}
export interface DictsPostParams {
  /**
   * 状态
   */
  status: number;
  /**
   * 名称
   */
  text: string;
  /**
   * 编码
   */
  code: string;
  /**
   * 描述
   */
  description: string;
  [k: string]: unknown;
}
/**
 * 字典
 */
export interface DictsPostResponse {
  /**
   * 标识
   */
  id: number;
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  text: string;
  /**
   * 描述
   */
  description: string;
  /**
   * 状态
   */
  status: number;
  /**
   * 删除？
   */
  deleted: boolean;
  [k: string]: unknown;
}
export interface DictsGetParams {
  /**
   * 编码
   */
  code?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 描述
   */
  description?: string;
  /**
   * 删除？
   */
  deleted?: string;
  [k: string]: unknown;
}
export interface DictsDictIdDeleteParams {
  [k: string]: unknown;
}
export interface DictsDictIdDeleteResponse {
  [k: string]: unknown;
}
export interface DictsDictIdPutParams {
  [k: string]: unknown;
}
export interface DictsDictIdPutResponse {
  /**
   * 字典标识
   */
  id?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 描述
   */
  description?: string;
  /**
   * 状态
   */
  status?: number;
  /**
   * 删除？
   */
  deleted?: boolean;
  [k: string]: unknown;
}
export interface DictDictIdGetParams {
  [k: string]: unknown;
}
export interface DictDictIdGetResponse {
  /**
   * 标识
   */
  id?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 描述
   */
  description?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 删除？
   */
  deleted?: string;
  [k: string]: unknown;
}
export interface DictsDictIditemsAsPageGetParams {
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 父亲
   */
  parent?: string;
  /**
   * 祖先
   */
  ancestors: string;
  /**
   * 深度
   */
  depth?: string;
  /**
   * 叶子
   */
  terminal?: string;
  /**
   * 当前页码
   */
  current: string;
  /**
   * 每页数量
   */
  size: string;
  [k: string]: unknown;
}
export interface DictsDictIditemsAsPageGetResponse {
  /**
   * 每页数量
   */
  size: number;
  /**
   * 当前页码
   */
  current: number;
  /**
   * 总页数
   */
  pages: number;
  /**
   * 总数目
   */
  total: number;
  /**
   * 字典项目列表
   */
  records: {
    /**
     * 字典项目标识
     */
    id?: number;
    /**
     * 字典标识
     */
    dictId?: number;
    /**
     * 编码
     */
    code?: string;
    /**
     * 类型
     */
    type?: string;
    /**
     * 名称
     */
    text?: string;
    /**
     * 有效范围
     */
    scope?: string;
    /**
     * 排号
     */
    rank?: number;
    /**
     * 状态
     */
    status?: number;
    /**
     * 父亲
     */
    parent?: number;
    /**
     * 祖先
     */
    ancestors?: string;
    /**
     * 深度
     */
    depth?: number;
    /**
     * 叶子
     */
    terminal?: boolean;
    /**
     * 删除？
     */
    removed?: boolean;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface DictsDictCodeitemsByCodeGetParams {
  [k: string]: unknown;
}
export interface DictsAsPageGetParams {
  /**
   * 编码
   */
  code?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 描述
   */
  description?: string;
  /**
   * 删除？
   */
  deleted?: string;
  /**
   * 当前页码
   */
  current: string;
  /**
   * 每页数量
   */
  size: string;
  [k: string]: unknown;
}
export interface DictsAsPageGetResponse {
  /**
   * 每页数量
   */
  size: number;
  /**
   * 当前页码
   */
  current: number;
  /**
   * 总页数
   */
  pages: number;
  /**
   * 总数量
   */
  total: number;
  /**
   * 字典列表
   */
  records: {
    /**
     * id
     */
    " id"?: number;
    /**
     * 编码
     */
    code?: string;
    /**
     * 名称
     */
    text?: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 状态
     */
    status?: number;
    /**
     * 删除
     */
    deleted: boolean;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
