/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Api {
  MemberIdKeypathGetResponse?: MemberIdKeypathGetResponse;
  MemberIdKeypathGetResponseAddress?: MemberIdKeypathGetResponseAddress1;
  MemberIdKeypathGetResponseInfo?: MemberIdKeypathGetResponseInfo1;
  MemberIdKeypathGetResponseInfoBody?: MemberIdKeypathGetResponseInfoBody1;
  MemberIdKeypathGetRequset?: MemberIdKeypathGetRequset;
  MemberupdatePostResponse?: MemberupdatePostResponse;
  MemberupdatePostResponseAddress?: MemberupdatePostResponseAddress1;
  MemberupdatePostResponseInfo?: MemberupdatePostResponseInfo1;
  MemberupdatePostResponseInfoBody?: MemberupdatePostResponseInfoBody1;
  MemberupdatePostRequset?: MemberupdatePostRequset;
}
export interface MemberIdKeypathGetResponse {
  /**
   * 姓名
   */
  name: string;
  /**
   * 地址列表
   */
  address: MemberIdKeypathGetResponseAddress[];
  info: MemberIdKeypathGetResponseInfo;
}
export interface MemberIdKeypathGetResponseAddress {
  /**
   * 城市
   */
  city: string;
  /**
   * 区
   */
  qu: string;
  /**
   * 门派
   */
  menpai: string;
}
export interface MemberIdKeypathGetResponseInfo {
  /**
   * 年龄
   */
  age: number;
  body: MemberIdKeypathGetResponseInfoBody;
}
/**
 * 身体信息
 */
export interface MemberIdKeypathGetResponseInfoBody {
  /**
   * 身高
   */
  height: string;
  /**
   * 体重
   */
  体重: string;
}
export interface MemberIdKeypathGetResponseAddress1 {
  /**
   * 城市
   */
  city: string;
  /**
   * 区
   */
  qu: string;
  /**
   * 门派
   */
  menpai: string;
}
export interface MemberIdKeypathGetResponseInfo1 {
  /**
   * 年龄
   */
  age: number;
  /**
   * 身体信息
   */
  body: {
    /**
     * 身高
     */
    height: string;
    /**
     * 体重
     */
    体重: string;
    [k: string]: unknown;
  };
}
export interface MemberIdKeypathGetResponseInfoBody1 {
  /**
   * 身高
   */
  height: string;
  /**
   * 体重
   */
  体重: string;
}
export interface MemberIdKeypathGetRequset {
  /**
   * 姓名
   */
  name: string;
  /**
   * 密码
   */
  password: string;
}
export interface MemberupdatePostResponse {
  /**
   * 姓名
   */
  name: string;
  /**
   * 地址列表
   */
  address: MemberupdatePostResponseAddress[];
  info: MemberupdatePostResponseInfo;
}
export interface MemberupdatePostResponseAddress {
  /**
   * 城市
   */
  city: string;
  /**
   * 区
   */
  qu: string;
  /**
   * 门派
   */
  menpai: string;
}
export interface MemberupdatePostResponseInfo {
  /**
   * 年龄
   */
  age: number;
  body: MemberupdatePostResponseInfoBody;
}
/**
 * 身体信息
 */
export interface MemberupdatePostResponseInfoBody {
  /**
   * 身高
   */
  height: string;
  /**
   * 体重
   */
  体重: string;
}
export interface MemberupdatePostResponseAddress1 {
  /**
   * 城市
   */
  city: string;
  /**
   * 区
   */
  qu: string;
  /**
   * 门派
   */
  menpai: string;
}
export interface MemberupdatePostResponseInfo1 {
  /**
   * 年龄
   */
  age: number;
  /**
   * 身体信息
   */
  body: {
    /**
     * 身高
     */
    height: string;
    /**
     * 体重
     */
    体重: string;
    [k: string]: unknown;
  };
}
export interface MemberupdatePostResponseInfoBody1 {
  /**
   * 身高
   */
  height: string;
  /**
   * 体重
   */
  体重: string;
}
export interface MemberupdatePostRequset {
  id: string;
}
