/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Api {
  DictsDictIditemsGetResponse?: DictsDictIditemsGetResponse;
  DictsDictIditemsGetRequset?: DictsDictIditemsGetRequset;
  DictsDictCodeitemsByCodeGetResponse?: DictsDictCodeitemsByCodeGetResponse;
  DictsDictCodeitemsByCodeGetRequset?: DictsDictCodeitemsByCodeGetRequset;
  DictsGetResponse?: DictsGetResponse;
  DictsGetRequset?: DictsGetRequset;
  DivisionsIdGetResponse?: DivisionsIdGetResponse;
  DivisionsIdGetRequset?: DivisionsIdGetRequset;
  DivisionsGetResponse?: DivisionsGetResponse;
  DivisionsGetRequset?: DivisionsGetRequset;
  OrganizationsGetResponse?: OrganizationsGetResponse;
  OrganizationsGetResponseSubOrganizationList?: OrganizationsGetResponseSubOrganizationList1;
  OrganizationsGetRequset?: OrganizationsGetRequset;
  ProductsGetResponse?: ProductsGetResponse;
  ProductsGetRequset?: ProductsGetRequset;
  ShopsGetResponse?: ShopsGetResponse;
  ShopsGetResponseAlarmList?: ShopsGetResponseAlarmList1;
  ShopsGetRequset?: ShopsGetRequset;
  ShopsIdGetResponse?: ShopsIdGetResponse;
  ShopsIdGetResponseBaseInfo?: ShopsIdGetResponseBaseInfo1;
  ShopsIdGetResponseMemberInfo?: ShopsIdGetResponseMemberInfo1;
  ShopsIdGetResponseSalesData?: ShopsIdGetResponseSalesData1;
  ShopsIdGetResponseSalesDataMontSalesData?: ShopsIdGetResponseSalesDataMontSalesData1;
  ShopsIdGetResponseSalesDataMontSalesDataProductSalesDataList?: ShopsIdGetResponseSalesDataMontSalesDataProductSalesDataList1;
  ShopsIdGetResponseSalesDataYearSalesData?: ShopsIdGetResponseSalesDataYearSalesData1;
  ShopsIdGetResponseSalesDataYearSalesDataProductSalesDataList?: ShopsIdGetResponseSalesDataYearSalesDataProductSalesDataList1;
  ShopsIdGetResponseActivityInfo?: ShopsIdGetResponseActivityInfo1;
  ShopsIdGetResponseActivityInfoActivityList?: ShopsIdGetResponseActivityInfoActivityList1;
  ShopsIdGetRequset?: ShopsIdGetRequset;
  VisitsummaryEmployeeCodeGetResponse?: VisitsummaryEmployeeCodeGetResponse;
  VisitsummaryEmployeeCodeGetRequset?: VisitsummaryEmployeeCodeGetRequset;
  VisitdetialsEmployeeCodeAsPageGetResponse?: VisitdetialsEmployeeCodeAsPageGetResponse;
  VisitdetialsEmployeeCodeAsPageGetResponseRecords?: VisitdetialsEmployeeCodeAsPageGetResponseRecords1;
  VisitdetialsEmployeeCodeAsPageGetRequset?: VisitdetialsEmployeeCodeAsPageGetRequset;
  VisitorganizationstatisticsGetResponse?: VisitorganizationstatisticsGetResponse;
  VisitorganizationstatisticsGetResponseSubOrgStatisticsList?: VisitorganizationstatisticsGetResponseSubOrgStatisticsList1;
  VisitorganizationstatisticsGetRequset?: VisitorganizationstatisticsGetRequset;
  VisitemployeestatisticsGetResponse?: VisitemployeestatisticsGetResponse;
  VisitemployeestatisticsGetResponseEmployeeStatisticsList?: VisitemployeestatisticsGetResponseEmployeeStatisticsList1;
  VisitemployeestatisticsGetRequset?: VisitemployeestatisticsGetRequset;
}
export interface DictsDictIditemsGetResponse {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除？
   */
  deteled?: boolean;
}
export interface DictsDictIditemsGetRequset {}
export interface DictsDictCodeitemsByCodeGetResponse {
  /**
   * 字典项目标识
   */
  id?: number;
  /**
   * 字典标识
   */
  dictId?: number;
  /**
   * 编码
   */
  code?: string;
  /**
   * 类型
   */
  type?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 有效范围
   */
  scope?: string;
  /**
   * 排号
   */
  rank?: number;
  /**
   * 状态
   */
  status?: number;
  /**
   * 父亲
   */
  parent?: number;
  /**
   * 祖先
   */
  ancestors?: string;
  /**
   * 深度
   */
  depth?: number;
  /**
   * 叶子
   */
  terminal?: boolean;
  /**
   * 删除
   */
  deleted?: boolean;
}
export interface DictsDictCodeitemsByCodeGetRequset {}
export interface DictsGetResponse {
  /**
   * 标识
   */
  id: number;
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  text: string;
  /**
   * 描述
   */
  description: string;
  /**
   * 状态
   */
  status: number;
  /**
   * 删除？
   */
  deleted: boolean;
}
export interface DictsGetRequset {
  /**
   * 编码
   */
  code?: string;
  /**
   * 名称
   */
  text?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 描述
   */
  description?: string;
  /**
   * 删除？
   */
  deleted?: string;
}
export interface DivisionsIdGetResponse {
  /**
   * 行政区ID
   */
  id: number;
  /**
   * 行政区编码
   */
  code: string;
  /**
   * 行政区名称
   */
  displayname: string;
  /**
   * 简称
   */
  shortname: string;
  /**
   * 全称
   */
  fullname: string;
  /**
   * 别名
   */
  alias: string;
  /**
   * 行政区父Id
   */
  parentId: number;
  /**
   * 层级
   */
  hierarchy: "1" | "2" | "3" | "4" | "5" | "6";
  /**
   * 排位
   */
  rank: number;
  /**
   * 状态
   */
  status: 10 | 20;
  /**
   * 经度
   */
  lng: number;
  /**
   * 纬度
   */
  lat: number;
  /**
   * 描述
   */
  description: string;
  /**
   * 祖先
   */
  ancestors: string;
  /**
   * 深度
   */
  depth: number;
  /**
   * 叶子
   */
  terminal: boolean;
}
export interface DivisionsIdGetRequset {}
export interface DivisionsGetResponse {
  /**
   * 行政区ID
   */
  id: number;
  /**
   * 行政区编码
   */
  code: string;
  /**
   * 行政区名称
   */
  displayname: string;
  /**
   * 行政区父Id
   */
  parentId: number;
  /**
   * 层级
   */
  hierarchy: "1" | "2" | "3" | "4" | "5" | "6";
  /**
   * 排位
   */
  rank: number;
  /**
   * 状态
   */
  status: 10 | 20;
}
export interface DivisionsGetRequset {
  /**
   * 行政区编码
   */
  code?: string;
  /**
   * 行政区父Id
   */
  parentId?: string;
  /**
   * 行政区名称
   */
  displayname?: string;
}
export interface OrganizationsGetResponse {
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 层级
   */
  hierarchy: string;
  /**
   * 父编码
   */
  parentCode: string;
  /**
   * 所有祖先（英文逗号分割）
   */
  ancestors: string;
  /**
   * 是否叶子（0-否；1-是）
   */
  terminal: number;
  /**
   * 状态
   */
  status: number;
  /**
   * 子组织列表
   */
  subOrganizationList: OrganizationsGetResponseSubOrganizationList[];
}
/**
 * 组织对象
 */
export interface OrganizationsGetResponseSubOrganizationList {
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 层级
   */
  hierarchy: string;
  /**
   * 父编码
   */
  parentCode: string;
  /**
   * 所有祖先（英文逗号分割）
   */
  ancestors: string;
  /**
   * 是否叶子（0-否；1-是）
   */
  terminal: number;
  /**
   * 状态
   */
  status: number;
}
export interface OrganizationsGetResponseSubOrganizationList1 {
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 层级
   */
  hierarchy: string;
  /**
   * 父编码
   */
  parentCode: string;
  /**
   * 所有祖先（英文逗号分割）
   */
  ancestors: string;
  /**
   * 是否叶子（0-否；1-是）
   */
  terminal: number;
  /**
   * 状态
   */
  status: number;
}
export interface OrganizationsGetRequset {
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 是否包含所有子节点（0-否；1-是）
   */
  includeChild: string;
}
export interface ProductsGetResponse {
  /**
   * 产品ID
   */
  id: number;
  /**
   * 产品编码
   */
  code: string;
  /**
   * 产品名称
   */
  name: string;
  /**
   * 产品图片
   */
  pictureUrl: string;
}
export interface ProductsGetRequset {}
export interface ShopsGetResponse {
  /**
   * 门店ID
   */
  id: number;
  /**
   * 门店编码
   */
  code: string;
  /**
   * 门店名称
   */
  name: string;
  /**
   * 省编码
   */
  provinceCode: string;
  /**
   * 省
   */
  provinceName: string;
  /**
   * 城市编码
   */
  cityCode: string;
  /**
   * 城市
   */
  cityName: string;
  /**
   * 区县编码
   */
  countyCode: string;
  /**
   * 区县
   */
  countyName: string;
  /**
   * 详细地址
   */
  address: string;
  /**
   * 经度
   */
  lng: number;
  /**
   * 纬度
   */
  lat: number;
  /**
   * 距离，单位米
   */
  distance: number;
  /**
   * 门店等级 10:A, 20:B, 30:C, 40:D
   */
  level: number;
  /**
   * 预警状态(0-7)  0：无预警；>0:有预警
   */
  alarmStatus: number;
  /**
   * 预警列表
   */
  alarmList?: ShopsGetResponseAlarmList[];
}
export interface ShopsGetResponseAlarmList {
  /**
   * 1.销量增幅大于50% 2.超过30天未拜访的门店  4.无动销门店
   */
  alarmCode: number;
  /**
   * 预警描述
   */
  alarmDesc?: string;
}
export interface ShopsGetResponseAlarmList1 {
  /**
   * 1.销量增幅大于50% 2.超过30天未拜访的门店  4.无动销门店
   */
  alarmCode: number;
  /**
   * 预警描述
   */
  alarmDesc?: string;
}
export interface ShopsGetRequset {
  /**
   * 门店名称.模糊匹配.
   */
  name?: string;
  /**
   * 经度
   */
  lng: string;
  /**
   * 纬度
   */
  lat: string;
  /**
   * 缩放距离
   */
  distance: string;
  /**
   * 门店等级列表  10:A, 20:B, 30:C, 40:D .多值以英文逗号分隔.
   */
  levels?: string;
  /**
   * 告警类型列表. 多值以英文逗号分隔.
   */
  alarmStatuses?: string;
}
export interface ShopsIdGetResponse {
  baseInfo: ShopsIdGetResponseBaseInfo;
  memberInfo: ShopsIdGetResponseMemberInfo;
  salesData: ShopsIdGetResponseSalesData;
  activityInfo: ShopsIdGetResponseActivityInfo;
}
/**
 * 门店基本信息
 */
export interface ShopsIdGetResponseBaseInfo {
  /**
   * 门店ID
   */
  id: number;
  /**
   * 门店编码
   */
  code: string;
  /**
   * 门店名称
   */
  name: string;
  /**
   * 省份编码
   */
  provinceCode: string;
  /**
   * 省份
   */
  province: string;
  /**
   * 城市编码
   */
  cityCode: string;
  /**
   * 城市
   */
  city: string;
  /**
   * 区县编码
   */
  areaCode: string;
  /**
   * 区县
   */
  area: string;
  /**
   * 详细地址
   */
  address: string;
  /**
   * 门店等级。10:A, 20:B, 30:C, 40:D
   */
  level: number;
  /**
   * 合作时间
   */
  effectiveDate: string;
  /**
   * 关联经理员工编码
   */
  employeeCode: string;
  /**
   * 关联经理员工姓名
   */
  employeeName: string;
  /**
   * 导购员
   */
  shoppingGuide: string;
  /**
   * 导购员电话
   */
  shoppingGuidePhone: string;
}
/**
 * 会员信息
 */
export interface ShopsIdGetResponseMemberInfo {
  /**
   * 当月新客数
   */
  monthNewMemberNum: number;
  /**
   * 年累计新客数
   */
  yearNewMemberNum: number;
}
/**
 * 销售数据
 */
export interface ShopsIdGetResponseSalesData {
  montSalesData: ShopsIdGetResponseSalesDataMontSalesData;
  yearSalesData: ShopsIdGetResponseSalesDataYearSalesData;
}
/**
 * 月销售数据
 */
export interface ShopsIdGetResponseSalesDataMontSalesData {
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
  /**
   * 产品销售数据列表
   */
  productSalesDataList: ShopsIdGetResponseSalesDataMontSalesDataProductSalesDataList[];
}
/**
 * 产品销售数据
 */
export interface ShopsIdGetResponseSalesDataMontSalesDataProductSalesDataList {
  /**
   * 产品编码
   */
  productCode: string;
  /**
   * 产品名称
   */
  productName: string;
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
}
/**
 * 年销售数据
 */
export interface ShopsIdGetResponseSalesDataYearSalesData {
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
  /**
   * 产品销售数据列表
   */
  productSalesDataList: ShopsIdGetResponseSalesDataYearSalesDataProductSalesDataList[];
}
/**
 * 产品销售数据
 */
export interface ShopsIdGetResponseSalesDataYearSalesDataProductSalesDataList {
  /**
   * 产品编码
   */
  productCode: string;
  /**
   * 产品名称
   */
  productName: string;
  /**
   * 总数
   */
  totalNum: string;
  /**
   * 总金额
   */
  totalAmount: string;
}
/**
 * 活动信息
 */
export interface ShopsIdGetResponseActivityInfo {
  /**
   * 年累计活动数
   */
  yearActivityNum: string;
  /**
   * 活动列表
   */
  activityList: ShopsIdGetResponseActivityInfoActivityList[];
}
/**
 * 活动对象
 */
export interface ShopsIdGetResponseActivityInfoActivityList {
  /**
   * 活动名称
   */
  activityName: string;
  /**
   * 开始时间
   */
  startTime: string;
  /**
   * 结束时间
   */
  endTime: string;
  /**
   * 是否为当月活动，1为当月活动，0为上个月活动
   */
  currentMonthActivity: number;
}
export interface ShopsIdGetResponseBaseInfo1 {
  /**
   * 门店ID
   */
  id: number;
  /**
   * 门店编码
   */
  code: string;
  /**
   * 门店名称
   */
  name: string;
  /**
   * 省份编码
   */
  provinceCode: string;
  /**
   * 省份
   */
  province: string;
  /**
   * 城市编码
   */
  cityCode: string;
  /**
   * 城市
   */
  city: string;
  /**
   * 区县编码
   */
  areaCode: string;
  /**
   * 区县
   */
  area: string;
  /**
   * 详细地址
   */
  address: string;
  /**
   * 门店等级。10:A, 20:B, 30:C, 40:D
   */
  level: number;
  /**
   * 合作时间
   */
  effectiveDate: string;
  /**
   * 关联经理员工编码
   */
  employeeCode: string;
  /**
   * 关联经理员工姓名
   */
  employeeName: string;
  /**
   * 导购员
   */
  shoppingGuide: string;
  /**
   * 导购员电话
   */
  shoppingGuidePhone: string;
}
export interface ShopsIdGetResponseMemberInfo1 {
  /**
   * 当月新客数
   */
  monthNewMemberNum: number;
  /**
   * 年累计新客数
   */
  yearNewMemberNum: number;
}
export interface ShopsIdGetResponseSalesData1 {
  /**
   * 月销售数据
   */
  montSalesData: {
    /**
     * 总数
     */
    totalNum: number;
    /**
     * 总金额
     */
    totalAmount: number;
    /**
     * 产品销售数据列表
     */
    productSalesDataList: {
      /**
       * 产品编码
       */
      productCode: string;
      /**
       * 产品名称
       */
      productName: string;
      /**
       * 总数
       */
      totalNum: number;
      /**
       * 总金额
       */
      totalAmount: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * 年销售数据
   */
  yearSalesData: {
    /**
     * 总数
     */
    totalNum: number;
    /**
     * 总金额
     */
    totalAmount: number;
    /**
     * 产品销售数据列表
     */
    productSalesDataList: {
      /**
       * 产品编码
       */
      productCode: string;
      /**
       * 产品名称
       */
      productName: string;
      /**
       * 总数
       */
      totalNum: string;
      /**
       * 总金额
       */
      totalAmount: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
}
export interface ShopsIdGetResponseSalesDataMontSalesData1 {
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
  /**
   * 产品销售数据列表
   */
  productSalesDataList: {
    /**
     * 产品编码
     */
    productCode: string;
    /**
     * 产品名称
     */
    productName: string;
    /**
     * 总数
     */
    totalNum: number;
    /**
     * 总金额
     */
    totalAmount: number;
    [k: string]: unknown;
  }[];
}
export interface ShopsIdGetResponseSalesDataMontSalesDataProductSalesDataList1 {
  /**
   * 产品编码
   */
  productCode: string;
  /**
   * 产品名称
   */
  productName: string;
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
}
export interface ShopsIdGetResponseSalesDataYearSalesData1 {
  /**
   * 总数
   */
  totalNum: number;
  /**
   * 总金额
   */
  totalAmount: number;
  /**
   * 产品销售数据列表
   */
  productSalesDataList: {
    /**
     * 产品编码
     */
    productCode: string;
    /**
     * 产品名称
     */
    productName: string;
    /**
     * 总数
     */
    totalNum: string;
    /**
     * 总金额
     */
    totalAmount: string;
    [k: string]: unknown;
  }[];
}
export interface ShopsIdGetResponseSalesDataYearSalesDataProductSalesDataList1 {
  /**
   * 产品编码
   */
  productCode: string;
  /**
   * 产品名称
   */
  productName: string;
  /**
   * 总数
   */
  totalNum: string;
  /**
   * 总金额
   */
  totalAmount: string;
}
export interface ShopsIdGetResponseActivityInfo1 {
  /**
   * 年累计活动数
   */
  yearActivityNum: string;
  /**
   * 活动列表
   */
  activityList: {
    /**
     * 活动名称
     */
    activityName: string;
    /**
     * 开始时间
     */
    startTime: string;
    /**
     * 结束时间
     */
    endTime: string;
    /**
     * 是否为当月活动，1为当月活动，0为上个月活动
     */
    currentMonthActivity: number;
    [k: string]: unknown;
  }[];
}
export interface ShopsIdGetResponseActivityInfoActivityList1 {
  /**
   * 活动名称
   */
  activityName: string;
  /**
   * 开始时间
   */
  startTime: string;
  /**
   * 结束时间
   */
  endTime: string;
  /**
   * 是否为当月活动，1为当月活动，0为上个月活动
   */
  currentMonthActivity: number;
}
export interface ShopsIdGetRequset {}
export interface VisitsummaryEmployeeCodeGetResponse {
  /**
   * 员工编号
   */
  employeeCode: string;
  /**
   * 员工名字
   */
  employeeName: string;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
}
export interface VisitsummaryEmployeeCodeGetRequset {
  /**
   * 年
   */
  year: string;
  /**
   * 月
   */
  month: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
}
export interface VisitdetialsEmployeeCodeAsPageGetResponse {
  /**
   * 每页数量
   */
  size: number;
  /**
   * 当前页码
   */
  current: number;
  /**
   * 总页数
   */
  pages: number;
  /**
   * 总数量
   */
  total: number;
  /**
   * 字典列表
   */
  records: VisitdetialsEmployeeCodeAsPageGetResponseRecords[];
}
export interface VisitdetialsEmployeeCodeAsPageGetResponseRecords {
  /**
   * 员工ID
   */
  employeeId: number;
  /**
   * 客户ID
   */
  customerId: number;
  /**
   * 客户编码
   */
  customerCode: string;
  /**
   * 客户名称
   */
  customerName: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
  /**
   * 拜访日期
   */
  visitDate: string;
  /**
   * 拜访时间
   */
  startTime: string;
  /**
   * 离店时间
   */
  endTime: string;
}
export interface VisitdetialsEmployeeCodeAsPageGetResponseRecords1 {
  /**
   * 员工ID
   */
  employeeId: number;
  /**
   * 客户ID
   */
  customerId: number;
  /**
   * 客户编码
   */
  customerCode: string;
  /**
   * 客户名称
   */
  customerName: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
  /**
   * 拜访日期
   */
  visitDate: string;
  /**
   * 拜访时间
   */
  startTime: string;
  /**
   * 离店时间
   */
  endTime: string;
}
export interface VisitdetialsEmployeeCodeAsPageGetRequset {
  /**
   * 年
   */
  year: string;
  /**
   * 月
   */
  month: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
}
export interface VisitorganizationstatisticsGetResponse {
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织名称
   */
  name: string;
  /**
   * 销售组织层级
   */
  hierarchy: string;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
  /**
   * 是否叶子节点
   */
  terminal: boolean;
  /**
   * 子组织拜访统计列表
   */
  subOrgStatisticsList?: VisitorganizationstatisticsGetResponseSubOrgStatisticsList[];
}
/**
 * 组织拜访统计
 */
export interface VisitorganizationstatisticsGetResponseSubOrgStatisticsList {
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织名称
   */
  name: string;
  /**
   * 销售组织层级
   */
  hierarchy: string;
  /**
   * 是否叶子节点
   */
  terminal: boolean;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
}
export interface VisitorganizationstatisticsGetResponseSubOrgStatisticsList1 {
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织名称
   */
  name: string;
  /**
   * 销售组织层级
   */
  hierarchy: string;
  /**
   * 是否叶子节点
   */
  terminal: boolean;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
}
export interface VisitorganizationstatisticsGetRequset {
  /**
   * 年
   */
  year: string;
  /**
   * 月
   */
  month: string;
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织层级
   */
  hierarchy: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
}
export interface VisitemployeestatisticsGetResponse {
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织名称
   */
  name: string;
  /**
   * 销售组织层级
   */
  hierarchy: number;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
  /**
   * 员工拜访统计列表
   */
  employeeStatisticsList: VisitemployeestatisticsGetResponseEmployeeStatisticsList[];
}
/**
 * 员工拜访统计
 */
export interface VisitemployeestatisticsGetResponseEmployeeStatisticsList {
  /**
   * 员工编码
   */
  employeeCode: string;
  /**
   * 员工姓名
   */
  employeeName: string;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
  /**
   * 员工ID
   */
  employeeId: string;
}
export interface VisitemployeestatisticsGetResponseEmployeeStatisticsList1 {
  /**
   * 员工编码
   */
  employeeCode: string;
  /**
   * 员工姓名
   */
  employeeName: string;
  /**
   * 目标数
   */
  targetNumber: number;
  /**
   * 拜访数
   */
  visitNumber: number;
  /**
   * 完成率
   */
  completionRate: number;
  /**
   * 员工ID
   */
  employeeId: string;
}
export interface VisitemployeestatisticsGetRequset {
  /**
   * 年
   */
  year: string;
  /**
   * 月
   */
  month: string;
  /**
   * 销售组织编码
   */
  code: string;
  /**
   * 销售组织层级
   */
  hierarchy: string;
  /**
   * 客户类别 10:门店, 20:经销商
   */
  customerCategory: string;
}
